# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_sale', models.FloatField(verbose_name='Total Sale')),
                ('card1', models.FloatField(verbose_name='Card Machine 1')),
                ('card2', models.FloatField(verbose_name='Card Machine 2')),
                ('card3', models.FloatField(verbose_name='Card Machine 3')),
                ('take_away', models.FloatField(verbose_name='Take Away')),
                ('meat', models.FloatField(verbose_name='Meat')),
                ('vegetables', models.FloatField(verbose_name='Vegetables')),
                ('fish', models.FloatField(verbose_name='Fish')),
                ('containers', models.FloatField(verbose_name='Containers')),
                ('beer', models.FloatField(verbose_name='Beer')),
                ('cash_carry', models.FloatField(verbose_name='Cash & Carry')),
                ('soft_drinks', models.FloatField(verbose_name='Soft Drinks')),
                ('credit', models.FloatField(verbose_name='Credit')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('miscellaneous', models.FloatField(verbose_name='Miscellaneous')),
                ('balance', models.FloatField(verbose_name='Balance')),
            ],
        ),
    ]
