# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thattukada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='balance',
            field=models.FloatField(blank=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='beer',
            field=models.FloatField(blank=True, verbose_name='Beer'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='card1',
            field=models.FloatField(blank=True, verbose_name='Card Machine 1'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='card2',
            field=models.FloatField(blank=True, verbose_name='Card Machine 2'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='card3',
            field=models.FloatField(blank=True, verbose_name='Card Machine 3'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='cash_carry',
            field=models.FloatField(blank=True, verbose_name='Cash & Carry'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='containers',
            field=models.FloatField(blank=True, verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='credit',
            field=models.FloatField(blank=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='fish',
            field=models.FloatField(blank=True, verbose_name='Fish'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='meat',
            field=models.FloatField(blank=True, verbose_name='Meat'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='miscellaneous',
            field=models.FloatField(blank=True, verbose_name='Miscellaneous'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='salary',
            field=models.FloatField(blank=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='soft_drinks',
            field=models.FloatField(blank=True, verbose_name='Soft Drinks'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='take_away',
            field=models.FloatField(blank=True, verbose_name='Take Away'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='total_sale',
            field=models.FloatField(blank=True, verbose_name='Total Sale'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='vegetables',
            field=models.FloatField(blank=True, verbose_name='Vegetables'),
        ),
    ]
